### PR TITLE
Adding secrets

### PR DESCRIPTION
**Pull request by andreaswittig**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by andreaswittig** [comment]
test

**Comment by andreaswittig** [comment]
test

**Comment by andreaswittig** [comment]
test

**Comment by andreaswittig** [comment]
@michaelwittig Any ideas why `test` is not triggering a test run?

**Comment by michaelwittig** [comment]
test

**Comment by michaelwittig** [comment]
test

**Review by michaelwittig — APPROVED** [review]

**Pull request merged**
